//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _28._01ui
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public Events()
        {
            this.Results = new HashSet<Results>();
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int Id { get; set; }
        public string EventName { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public string Location { get; set; }
        public Nullable<int> IdEventType { get; set; }
        public string EventDesc { get; set; }
        public string EventImg { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> TicketsRemain { get; set; }
    
        public virtual EventType EventType { get; set; }
        public virtual ICollection<Results> Results { get; set; }
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
