//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _28._01ui
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admission> Admission { get; set; }
        public DbSet<EventGallery> EventGallery { get; set; }
        public DbSet<Events> Events { get; set; }
        public DbSet<EventType> EventType { get; set; }
        public DbSet<PilotCar> PilotCar { get; set; }
        public DbSet<PilotRoles> PilotRoles { get; set; }
        public DbSet<Pilots> Pilots { get; set; }
        public DbSet<Results> Results { get; set; }
        public DbSet<Teams> Teams { get; set; }
        public DbSet<Ticket> Ticket { get; set; }
        public DbSet<UserRole> UserRole { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
