//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _28._01ui
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pilots
    {
        public Pilots()
        {
            this.PilotCar = new HashSet<PilotCar>();
            this.Results = new HashSet<Results>();
        }
    
        public int Id { get; set; }
        public string PilotName { get; set; }
        public Nullable<System.DateTime> PilotBirthDate { get; set; }
        public string Bio { get; set; }
        public string City { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string PilotImg { get; set; }
    
        public virtual ICollection<PilotCar> PilotCar { get; set; }
        public virtual PilotRoles PilotRoles { get; set; }
        public virtual Teams Teams { get; set; }
        public virtual ICollection<Results> Results { get; set; }
    }
}
