//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _28._01ui
{
    using System;
    using System.Collections.Generic;
    
    public partial class PilotCar
    {
        public PilotCar()
        {
            this.Admission = new HashSet<Admission>();
            this.Pilots = new HashSet<Pilots>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Engine { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<int> HorsePower { get; set; }
    
        public virtual ICollection<Admission> Admission { get; set; }
        public virtual ICollection<Pilots> Pilots { get; set; }
    }
}
